### ISSUE TITLE
Failed to build Tearing under SOFA

### ISSUE THREAD

**Issue by xhtsansiro** [InfinyTech3D/Tearing#35]
Hi, 
I encounter a problem when trying to install Tearing plugin under SOFA by following the steps described here: [](https://www.sofa-framework.org/community/doc/getting-started/video-tutorials/how-to-compile-a-plugin/).

The terminal outputs a fatal error " sofa/component/constraint/projective/FixedProjectiveConstraint.h:  No such file or directory". and the plugin cannot be built successfully.  Following pics show the detail problem. 

Is there any other plugins which is necessary for building Tearing plugin. Any help is really appreciated. 

![75b6bb6fe96ffec620b6519e125a733fe5a626b6a739d117f3416a5c393c516cL2hvbWUveGh0c2Fuc2lyby8uY29uZmlnL0RpbmdUYWxrLzE2MjczNjQ2OTJfdjIvSW1hZ2VGaWxlcy8xNzEwOTk5NTMzOTQ2XzE3MTA5OTk1MzI0ODQuanBn](https://github.com/InfinyTech3D/Tearing/assets/55890308/c7e2558c-db41-437d-8390-417c172a7c77)
![df7e2d62821fb8940bce3d911f34477ce80f5f048a57ad4fd6b5e47ec82c6263L2hvbWUveGh0c2Fuc2lyby8uY29uZmlnL0RpbmdUYWxrLzE2MjczNjQ2OTJfdjIvSW1hZ2VGaWxlcy8xNzEwOTk5NTExMDQ2XzE3MTA5OTk1MDg3MDEuanBn](https://github.com/InfinyTech3D/Tearing/assets/55890308/c1c6a2c4-c661-4a67-91a7-6a3437540255)

**Comment by rmolazem** [comment]
Hi @xhtsansiro,

Could you please let us know which version of Sofa you are using? 
We recommend using SOFA (master) at least 23.12 with the Tearing plugin (master).

**Comment by xhtsansiro** [comment]
Hi, @rmolazem ,

Thanks for your reply. I use the version 23.12 by "git clone -b v23.12.01 https://github.com/sofa-framework/sofa.git sofa/src" , and Tearing plugin is main branch.

**Comment by rmolazem** [comment]
Hi @xhtsansiro,

Ah yes, the error happens due to recent modifications in the Tearing plugin, which align with the updates made in Sofa.
You have two options:
1. You can choose to stick with your current Sofa version (23.12). However,  to avoid compatibility issues, it's essential to ensure that you also use the corresponding **Tearing plugin version (23.12)**.
2. Alternatively, if you wish to incorporate the latest modifications, you keep this latest version of the Tearing plugin, but
you need to clone **Sofa from the master branch**.

**Comment by xhtsansiro** [comment]
Thank you, It solved the issue.
